name: 发布 BLE 配网页面

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 获取源码
        uses: actions/checkout@v4
      - name: 配置 Pages
        uses: actions/configure-pages@v5
      - name: 准备网页
        uses: actions/upload-pages-artifact@v3
        with:
          path: web
      - name: 发布网页
        id: deployment
        uses: actions/deploy-pages@v4
